"""empty message

Revision ID: b4cbc9904574
Revises: 413307aaafdf
Create Date: 2018-02-14 14:56:31.865153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4cbc9904574'
down_revision = '413307aaafdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_cognito_id_key', 'users', type_='unique')
    op.drop_column('users', 'cognito_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('cognito_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.create_unique_constraint('users_cognito_id_key', 'users', ['cognito_id'])
    # ### end Alembic commands ###
